FROM alpine:edge
ARG VERSION=dev
RUN apk --update upgrade \
  && apk add ca-certificates \
  && update-ca-certificates \
  && rm -rf /var/cache/apk/* \
  && wget https://github.com/emilevauge/traefik/releases/download/$VERSION/traefik \
  && chmod +x traefik
EXPOSE 80
ENTRYPOINT ["/traefik"]
CMD ["--help"]
